version: '3'
services:
  jupyterlab:
    container_name: philab_root_container
    build:
      context: .
      dockerfile: "Dockerfile"
    user: philab_member
    volumes:
      - ./working:/home/philab_member/working
      - ./input:/home/philab_member/input:ro
      - ./output:/home/philab_member/output
      - ./html:/home/philab_member/html
    ports:
      #your host port : container port
      - "8888:8888"
      - "6006:6006"
    environment:
      TZ: Asia/Tokyo
    command:
      /bin/bash -c "jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.notebook_dir='/home/philab_member/working' --NotebookApp.token=''"
