version: '3'
services:
  jupyterlab:
    build:
      context: .
      dockerfile: "Dockerfile"
    user: philab_member
    volumes:
      - ./working:/home/philab_member/working
      - ./input:/home/philab_member/input:ro
      - ./output:/home/philab_member/output
      - ./html:/home/philab_member/html
    ports:
      - "8890:8888"
      - "6006:6006"
    environment:
      TZ: Asia/Tokyo
    command:
      jupyter lab
          --ip=0.0.0.0
          --allow-root
          --no-browser
          --NotebookApp.notebook_dir='/home/philab_member/working'
          --NotebookApp.token=''
